apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: boot-app
  name: boot-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boot-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: boot-app
    spec:
      containers:
      - image: dvkdoc/the-boot:0.1
        imagePullPolicy: IfNotPresent
        name: boot-app
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: boot-app
  name: boot-app
  namespace: default
spec:
  ports:
  - nodePort: 32681
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: boot-app
  sessionAffinity: None
  type: LoadBalancer