apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: the-boot-application
  name: the-boot-application
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8082
  selector:
    io.kompose.service: the-boot-application
